### ISSUE TITLE
Probleme mit Pfade

### ISSUE THREAD

**Issue by Sysix** [RexDude/magnific_popup#7]
Hallo Dude,

hab das erste mal das AddOn installiert und gleich paar Probleme bekommen :)
In Kombination mit seo42 und einem Unterpunkt (page/subpage.html) passen alle Pfade nichtmehr richtig. Die CSS/JS Dateien werden nicht geladen und die `$imageUrl` ist auch falsch.

Kannst du bitte nachschauen und ggf. ein Update hinterherziehen ?

Gruß Sysix

EDIT: ich benutze kein baseurl und möchte es auch nicht benutzen^^

**Comment by RexDude** [comment]
Thx!
